// Error codes and constants
export const ERROR_CODES = {
  SUCCESS: 0,
  INVALID_PARAMS: 1001,
  MISSING_PARAMS: 1002,
  INVALID_FORMAT: 1003,
  UNAUTHORIZED: 2001,
  TOKEN_EXPIRED: 2002,
  TOKEN_INVALID: 2003,
  PERMISSION_DENIED: 2004,
  ACCOUNT_DISABLED: 2005,
  SINGLE_DEVICE_LIMIT: 2006,
  ACCOUNT_LOCKED: 2007,
  USER_NOT_FOUND: 3001,
  PASSWORD_ERROR: 3002,
  PHONE_EXISTS: 3003,
  STUDENT_NOT_FOUND: 3004,
  CLASS_NOT_FOUND: 3005,
  RECIPE_NOT_FOUND: 4001,
  RECIPE_ALREADY_EXISTS: 4002,
  RECIPE_SAVE_FAILED: 4003,
  RECIPE_DELETE_FAILED: 4004,
  VERSION_CONFLICT: 4005,
  FILE_UPLOAD_FAILED: 5001,
  FILE_TOO_LARGE: 5002,
  INVALID_FILE_TYPE: 5003,
  FILE_COMPRESS_FAILED: 5004,
  SCHOOL_NOT_FOUND: 6001,
  SEMESTER_NOT_FOUND: 6002,
  ARCHIVE_CREATE_FAILED: 7001,
  ARCHIVE_NOT_FOUND: 7002,
  SYSTEM_ERROR: 9001,
  NETWORK_ERROR: 9002,
  SERVICE_UNAVAILABLE: 9003,
};

export const ERROR_MESSAGES = {
  [ERROR_CODES.SUCCESS]: { message: '操作成功', userMessage: '操作成功' },
  [ERROR_CODES.INVALID_PARAMS]: { message: '参数错误', userMessage: '请检查输入信息是否正确' },
  [ERROR_CODES.MISSING_PARAMS]: { message: '缺少必要参数', userMessage: '请填写完整信息' },
  [ERROR_CODES.INVALID_FORMAT]: { message: '格式错误', userMessage: '输入格式不正确，请检查后重试' },
  [ERROR_CODES.UNAUTHORIZED]: { message: '未登录', userMessage: '请先登录' },
  [ERROR_CODES.TOKEN_EXPIRED]: { message: '登录已过期', userMessage: '登录已过期，请重新登录' },
  [ERROR_CODES.TOKEN_INVALID]: { message: '无效的登录凭证', userMessage: '登录状态异常，请重新登录' },
  [ERROR_CODES.PERMISSION_DENIED]: { message: '权限不足', userMessage: '您没有权限执行此操作' },
  [ERROR_CODES.ACCOUNT_DISABLED]: { message: '账号已被禁用', userMessage: '您的账号已被禁用，请联系管理员' },
  [ERROR_CODES.SINGLE_DEVICE_LIMIT]: { message: '账号在其他设备登录', userMessage: '您的账号已在其他设备登录，请重新登录' },
  [ERROR_CODES.ACCOUNT_LOCKED]: { message: '账号已锁定', userMessage: '账号已被锁定，请稍后再试' },
  [ERROR_CODES.USER_NOT_FOUND]: { message: '用户不存在', userMessage: '用户不存在，请检查输入' },
  [ERROR_CODES.PASSWORD_ERROR]: { message: '密码错误', userMessage: '密码错误，请重新输入' },
  [ERROR_CODES.PHONE_EXISTS]: { message: '手机号已注册', userMessage: '该手机号已被注册，请直接登录' },
  [ERROR_CODES.STUDENT_NOT_FOUND]: { message: '学生信息不存在', userMessage: '学生信息不存在，请核对姓名、身份证号和班级' },
  [ERROR_CODES.CLASS_NOT_FOUND]: { message: '班级不存在', userMessage: '班级信息不存在，请重新选择' },
  [ERROR_CODES.RECIPE_NOT_FOUND]: { message: '食谱不存在', userMessage: '暂无食谱信息' },
  [ERROR_CODES.RECIPE_ALREADY_EXISTS]: { message: '食谱已存在', userMessage: '该日期已有食谱，请使用更新功能' },
  [ERROR_CODES.RECIPE_SAVE_FAILED]: { message: '食谱保存失败', userMessage: '保存失败，请稍后重试' },
  [ERROR_CODES.RECIPE_DELETE_FAILED]: { message: '食谱删除失败', userMessage: '删除失败，请稍后重试' },
  [ERROR_CODES.VERSION_CONFLICT]: { message: '版本冲突', userMessage: '食谱已被他人修改，请刷新后重试' },
  [ERROR_CODES.FILE_UPLOAD_FAILED]: { message: '文件上传失败', userMessage: '文件上传失败，请重试' },
  [ERROR_CODES.FILE_TOO_LARGE]: { message: '文件过大', userMessage: '文件大小超出限制，请压缩后上传' },
  [ERROR_CODES.INVALID_FILE_TYPE]: { message: '文件类型不支持', userMessage: '不支持该文件类型，请上传jpg/png/mp4格式' },
  [ERROR_CODES.FILE_COMPRESS_FAILED]: { message: '文件压缩失败', userMessage: '文件处理失败，请重试' },
  [ERROR_CODES.SCHOOL_NOT_FOUND]: { message: '学校不存在', userMessage: '学校信息不存在' },
  [ERROR_CODES.SEMESTER_NOT_FOUND]: { message: '学期不存在', userMessage: '学期信息不存在' },
  [ERROR_CODES.ARCHIVE_CREATE_FAILED]: { message: '归档创建失败', userMessage: '归档创建失败，请稍后重试' },
  [ERROR_CODES.ARCHIVE_NOT_FOUND]: { message: '归档不存在', userMessage: '归档文件不存在' },
  [ERROR_CODES.SYSTEM_ERROR]: { message: '系统错误', userMessage: '系统繁忙，请稍后重试' },
  [ERROR_CODES.NETWORK_ERROR]: { message: '网络错误', userMessage: '网络连接失败，请检查网络后重试' },
  [ERROR_CODES.SERVICE_UNAVAILABLE]: { message: '服务不可用', userMessage: '服务暂时不可用，请稍后重试' },
};

export const USER_TYPES = {
  TEACHER: 'teacher',
  PARENT: 'parent',
  ADMIN: 'admin',
};

export const RECIPE_TYPES = {
  DAILY: 'daily',
  WEEKLY: 'weekly',
};

export const MEDIA_TYPES = {
  IMAGE: 'image',
  VIDEO: 'video',
};

export const LOG_ACTIONS = {
  LOGIN: 'login',
  LOGOUT: 'logout',
  CREATE_RECIPE: 'create_recipe',
  UPDATE_RECIPE: 'update_recipe',
  DELETE_RECIPE: 'delete_recipe',
  UPLOAD_FILE: 'upload_file',
  DELETE_FILE: 'delete_file',
  ROLLBACK_RECIPE: 'rollback_recipe',
  CREATE_USER: 'create_user',
  UPDATE_USER: 'update_user',
  DELETE_USER: 'delete_user',
  ARCHIVE_CREATE: 'archive_create',
  ORPHAN_CLEANUP: 'orphan_cleanup',
};
